version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 10
    groups:
      python-runtime-dependencies:
        dependency-type: "production"
      python-development-dependencies:
        dependency-type: "development"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:30"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 5
