"""Bundled starter themes shipped with the application."""

from __future__ import annotations

from dataclasses import dataclass

from .theme_builder import normalize_theme_settings


@dataclass(frozen=True)
class StarterThemeSpec:
    name: str
    description: str
    values: dict[str, object]


def _theme(overrides: dict[str, object]) -> dict[str, object]:
    payload = {
        "selected_name": "",
        "custom_qss": "",
        "auto_contrast_enabled": True,
    }
    payload.update(overrides)
    return normalize_theme_settings(payload)


STARTER_THEME_SPECS: tuple[StarterThemeSpec, ...] = (
    StarterThemeSpec(
        name="Apple Light",
        description="A clean macOS-inspired light theme with soft panels, subtle chrome, and Apple-style blue accents.",
        values=_theme(
            {
                "font_size": 10,
                "dialog_title_font_size": 14,
                "section_title_font_size": 12,
                "secondary_text_font_size": 9,
                "window_bg": "#F5F5F7",
                "window_fg": "#1D1D1F",
                "panel_bg": "#FFFFFF",
                "panel_alt_bg": "#ECECF1",
                "border_color": "#D2D2D7",
                "accent": "#0A84FF",
                "selection_bg": "#D9ECFF",
                "selection_fg": "#0F172A",
                "secondary_text": "#6E6E73",
                "hint_text": "#8E8E93",
                "link_color": "#0071E3",
                "tooltip_bg": "#FFFFFF",
                "tooltip_fg": "#1D1D1F",
                "tooltip_border": "#D2D2D7",
                "overlay_bg": "#E7EEF8",
                "overlay_fg": "#1D1D1F",
                "button_bg": "#FFFFFF",
                "button_fg": "#1D1D1F",
                "button_border": "#C7C7CC",
                "button_hover_bg": "#F2F7FF",
                "button_hover_fg": "#1D1D1F",
                "button_hover_border": "#0A84FF",
                "button_pressed_bg": "#0A84FF",
                "button_pressed_fg": "#FFFFFF",
                "button_pressed_border": "#0066CC",
                "button_disabled_bg": "#F0F0F2",
                "button_disabled_fg": "#8E8E93",
                "button_disabled_border": "#D2D2D7",
                "help_button_bg": "#0A84FF",
                "help_button_fg": "#FFFFFF",
                "help_button_border": "#0066CC",
                "input_bg": "#FFFFFF",
                "input_fg": "#1D1D1F",
                "input_border": "#C7C7CC",
                "input_focus_bg": "#FFFFFF",
                "input_focus_fg": "#1D1D1F",
                "input_focus_border": "#0A84FF",
                "input_disabled_bg": "#F2F2F4",
                "input_disabled_fg": "#8E8E93",
                "input_disabled_border": "#D2D2D7",
                "placeholder_fg": "#8E8E93",
                "indicator_bg": "#FFFFFF",
                "indicator_border": "#A1A1AA",
                "indicator_checked_bg": "#0A84FF",
                "indicator_checked_border": "#0066CC",
                "table_bg": "#FFFFFF",
                "table_fg": "#1D1D1F",
                "table_alt_bg": "#F8F8FA",
                "table_border": "#D2D2D7",
                "table_grid": "#E5E5EA",
                "table_hover_bg": "#EEF5FF",
                "scrollbar_bg": "#ECECF1",
                "scrollbar_handle_bg": "#B6B6BD",
                "scrollbar_handle_hover_bg": "#8F8F97",
                "progress_bg": "#E5E5EA",
                "progress_chunk_bg": "#0A84FF",
                "menu_bg": "#FFFFFF",
                "menu_fg": "#1D1D1F",
                "menu_border": "#D2D2D7",
                "menu_selected_bg": "#D9ECFF",
                "menu_selected_fg": "#0F172A",
                "header_bg": "#EFF0F4",
                "header_fg": "#1D1D1F",
                "action_ribbon_bg": "#E8F2FF",
                "action_ribbon_fg": "#1D1D1F",
                "action_ribbon_border": "#8CB9F7",
                "tab_bg": "#ECECF1",
                "tab_fg": "#444446",
                "tab_border": "#D2D2D7",
                "tab_hover_bg": "#F5F7FB",
                "tab_hover_fg": "#1D1D1F",
                "tab_hover_border": "#B7C9E4",
                "tab_selected_bg": "#FFFFFF",
                "tab_selected_fg": "#1D1D1F",
                "tab_selected_border": "#0A84FF",
                "panel_radius": 10,
                "button_radius": 8,
                "help_button_radius": 6,
                "input_radius": 8,
                "table_radius": 8,
                "tab_radius": 10,
                "menu_radius": 10,
                "help_button_size": 11,
            }
        ),
    ),
    StarterThemeSpec(
        name="Apple Dark",
        description="A readable macOS-inspired dark palette with graphite surfaces and clear blue focus accents.",
        values=_theme(
            {
                "font_size": 10,
                "dialog_title_font_size": 14,
                "section_title_font_size": 12,
                "secondary_text_font_size": 9,
                "window_bg": "#1C1C1E",
                "window_fg": "#F5F5F7",
                "panel_bg": "#2C2C2E",
                "panel_alt_bg": "#3A3A3C",
                "border_color": "#4A4A4F",
                "accent": "#0A84FF",
                "selection_bg": "#245B93",
                "selection_fg": "#F9FAFB",
                "secondary_text": "#B0B0B5",
                "hint_text": "#8E8E93",
                "link_color": "#64D2FF",
                "tooltip_bg": "#2C2C2E",
                "tooltip_fg": "#F5F5F7",
                "tooltip_border": "#4A4A4F",
                "overlay_bg": "#3A4E66",
                "overlay_fg": "#F9FAFB",
                "button_bg": "#3A3A3C",
                "button_fg": "#F5F5F7",
                "button_border": "#5A5A5F",
                "button_hover_bg": "#454548",
                "button_hover_fg": "#FFFFFF",
                "button_hover_border": "#0A84FF",
                "button_pressed_bg": "#0A84FF",
                "button_pressed_fg": "#FFFFFF",
                "button_pressed_border": "#409CFF",
                "button_disabled_bg": "#2C2C2E",
                "button_disabled_fg": "#8E8E93",
                "button_disabled_border": "#4A4A4F",
                "help_button_bg": "#0A84FF",
                "help_button_fg": "#FFFFFF",
                "help_button_border": "#409CFF",
                "input_bg": "#2C2C2E",
                "input_fg": "#F5F5F7",
                "input_border": "#545458",
                "input_focus_bg": "#2F2F31",
                "input_focus_fg": "#FFFFFF",
                "input_focus_border": "#0A84FF",
                "input_disabled_bg": "#252527",
                "input_disabled_fg": "#8E8E93",
                "input_disabled_border": "#444448",
                "placeholder_fg": "#8E8E93",
                "indicator_bg": "#2C2C2E",
                "indicator_border": "#8E8E93",
                "indicator_checked_bg": "#0A84FF",
                "indicator_checked_border": "#409CFF",
                "table_bg": "#1F1F22",
                "table_fg": "#F5F5F7",
                "table_alt_bg": "#26262A",
                "table_border": "#4A4A4F",
                "table_grid": "#3A3A3C",
                "table_hover_bg": "#303B4C",
                "scrollbar_bg": "#2C2C2E",
                "scrollbar_handle_bg": "#5A5A5F",
                "scrollbar_handle_hover_bg": "#78787D",
                "progress_bg": "#3A3A3C",
                "progress_chunk_bg": "#0A84FF",
                "menu_bg": "#2C2C2E",
                "menu_fg": "#F5F5F7",
                "menu_border": "#4A4A4F",
                "menu_selected_bg": "#245B93",
                "menu_selected_fg": "#FFFFFF",
                "header_bg": "#2F2F31",
                "header_fg": "#F5F5F7",
                "action_ribbon_bg": "#153C61",
                "action_ribbon_fg": "#F5F5F7",
                "action_ribbon_border": "#4DA3FF",
                "tab_bg": "#2A2A2D",
                "tab_fg": "#C7C7CC",
                "tab_border": "#4A4A4F",
                "tab_hover_bg": "#343437",
                "tab_hover_fg": "#FFFFFF",
                "tab_hover_border": "#5A5A5F",
                "tab_selected_bg": "#1F1F22",
                "tab_selected_fg": "#F9FAFB",
                "tab_selected_border": "#0A84FF",
                "panel_radius": 10,
                "button_radius": 8,
                "help_button_radius": 6,
                "input_radius": 8,
                "table_radius": 8,
                "tab_radius": 10,
                "menu_radius": 10,
                "help_button_size": 11,
            }
        ),
    ),
    StarterThemeSpec(
        name="High Visibility",
        description="A high-contrast accessibility preset with enlarged type, heavier borders, and strong yellow emphasis.",
        values=_theme(
            {
                "font_size": 14,
                "dialog_title_font_size": 24,
                "section_title_font_size": 18,
                "secondary_text_font_size": 13,
                "window_bg": "#000000",
                "window_fg": "#FFFFFF",
                "panel_bg": "#000000",
                "panel_alt_bg": "#111111",
                "border_color": "#FFFFFF",
                "accent": "#FFD60A",
                "selection_bg": "#FFD60A",
                "selection_fg": "#000000",
                "secondary_text": "#F1F5F9",
                "hint_text": "#E5E7EB",
                "link_color": "#7FDBFF",
                "tooltip_bg": "#000000",
                "tooltip_fg": "#FFFFFF",
                "tooltip_border": "#FFD60A",
                "overlay_bg": "#FFD60A",
                "overlay_fg": "#000000",
                "button_bg": "#000000",
                "button_fg": "#FFFFFF",
                "button_border": "#FFD60A",
                "button_hover_bg": "#FFD60A",
                "button_hover_fg": "#000000",
                "button_hover_border": "#FFFFFF",
                "button_pressed_bg": "#FFFFFF",
                "button_pressed_fg": "#000000",
                "button_pressed_border": "#FFD60A",
                "button_disabled_bg": "#111111",
                "button_disabled_fg": "#BFBFBF",
                "button_disabled_border": "#808080",
                "help_button_bg": "#FFD60A",
                "help_button_fg": "#000000",
                "help_button_border": "#FFFFFF",
                "help_button_hover_bg": "#FFF176",
                "help_button_hover_fg": "#000000",
                "help_button_hover_border": "#FFFFFF",
                "help_button_pressed_bg": "#FFFFFF",
                "help_button_pressed_fg": "#000000",
                "help_button_pressed_border": "#FFD60A",
                "input_bg": "#000000",
                "input_fg": "#FFFFFF",
                "input_border": "#FFFFFF",
                "input_focus_bg": "#000000",
                "input_focus_fg": "#FFFFFF",
                "input_focus_border": "#FFD60A",
                "input_disabled_bg": "#111111",
                "input_disabled_fg": "#BFBFBF",
                "input_disabled_border": "#808080",
                "placeholder_fg": "#D4D4D8",
                "indicator_bg": "#000000",
                "indicator_border": "#FFFFFF",
                "indicator_checked_bg": "#FFD60A",
                "indicator_checked_border": "#FFFFFF",
                "table_bg": "#000000",
                "table_fg": "#FFFFFF",
                "table_alt_bg": "#101010",
                "table_border": "#FFFFFF",
                "table_grid": "#FFD60A",
                "table_hover_bg": "#1C1C1C",
                "scrollbar_bg": "#111111",
                "scrollbar_handle_bg": "#FFD60A",
                "scrollbar_handle_hover_bg": "#FFF176",
                "progress_bg": "#111111",
                "progress_chunk_bg": "#FFD60A",
                "menu_bg": "#000000",
                "menu_fg": "#FFFFFF",
                "menu_border": "#FFFFFF",
                "menu_selected_bg": "#FFD60A",
                "menu_selected_fg": "#000000",
                "header_bg": "#111111",
                "header_fg": "#FFFFFF",
                "action_ribbon_bg": "#FFD60A",
                "action_ribbon_fg": "#000000",
                "action_ribbon_border": "#FFFFFF",
                "tab_bg": "#111111",
                "tab_fg": "#FFFFFF",
                "tab_border": "#FFFFFF",
                "tab_hover_bg": "#1F1F1F",
                "tab_hover_fg": "#FFFFFF",
                "tab_hover_border": "#FFD60A",
                "tab_selected_bg": "#FFD60A",
                "tab_selected_fg": "#000000",
                "tab_selected_border": "#FFFFFF",
                "border_width": 2,
                "panel_radius": 10,
                "button_radius": 10,
                "button_padding_v": 7,
                "button_padding_h": 14,
                "help_button_size": 32,
                "help_button_radius": 16,
                "input_radius": 8,
                "input_padding_v": 6,
                "input_padding_h": 8,
                "indicator_size": 18,
                "table_radius": 8,
                "scrollbar_thickness": 16,
                "progress_radius": 8,
                "header_padding_v": 7,
                "header_padding_h": 10,
                "tab_radius": 10,
                "menu_radius": 8,
            }
        ),
    ),
    StarterThemeSpec(
        name="Aeon Emerald Gold",
        description="A deep emerald-and-gold palette inspired by the Aeon Cosmowyn artwork, with luminous teal surfaces and warm metallic highlights.",
        values=_theme(
            {
                "font_size": 10,
                "dialog_title_font_size": 14,
                "section_title_font_size": 12,
                "secondary_text_font_size": 9,
                "window_bg": "#0E2F2C",
                "window_fg": "#EAF4EE",
                "panel_bg": "#154440",
                "panel_alt_bg": "#1D504A",
                "border_color": "#2F6A64",
                "accent": "#D8B35A",
                "selection_bg": "#266E67",
                "selection_fg": "#F8FBF9",
                "secondary_text": "#B7CBC3",
                "hint_text": "#8FB1A6",
                "link_color": "#E7C66E",
                "tooltip_bg": "#173C38",
                "tooltip_fg": "#FFF9E9",
                "tooltip_border": "#8B7440",
                "overlay_bg": "#4D5644",
                "overlay_fg": "#FFF9E9",
                "button_bg": "#1C5E58",
                "button_fg": "#F8FBF9",
                "button_border": "#2D7D74",
                "button_hover_bg": "#24726A",
                "button_hover_fg": "#FFFFFF",
                "button_hover_border": "#D8B35A",
                "button_pressed_bg": "#D8B35A",
                "button_pressed_fg": "#1D241A",
                "button_pressed_border": "#F0D690",
                "button_disabled_bg": "#244641",
                "button_disabled_fg": "#90A79F",
                "button_disabled_border": "#42625D",
                "help_button_bg": "#D8B35A",
                "help_button_fg": "#1D241A",
                "help_button_border": "#F0D690",
                "help_button_hover_bg": "#E6C878",
                "help_button_hover_fg": "#192018",
                "help_button_hover_border": "#FFF0C0",
                "help_button_pressed_bg": "#B78F3A",
                "help_button_pressed_fg": "#FFF9E9",
                "help_button_pressed_border": "#E7C66E",
                "input_bg": "#113A36",
                "input_fg": "#EAF4EE",
                "input_border": "#2F6A64",
                "input_focus_bg": "#154440",
                "input_focus_fg": "#F8FBF9",
                "input_focus_border": "#D8B35A",
                "input_disabled_bg": "#17312E",
                "input_disabled_fg": "#86A59D",
                "input_disabled_border": "#365451",
                "placeholder_fg": "#7FA39B",
                "indicator_bg": "#113A36",
                "indicator_border": "#8FB1A6",
                "indicator_checked_bg": "#D8B35A",
                "indicator_checked_border": "#F0D690",
                "table_bg": "#103632",
                "table_fg": "#EAF4EE",
                "table_alt_bg": "#143E39",
                "table_border": "#2F6A64",
                "table_grid": "#234F4A",
                "table_hover_bg": "#1C5E58",
                "scrollbar_bg": "#143632",
                "scrollbar_handle_bg": "#34756D",
                "scrollbar_handle_hover_bg": "#479089",
                "progress_bg": "#234F4A",
                "progress_chunk_bg": "#D8B35A",
                "menu_bg": "#113935",
                "menu_fg": "#F2F7F4",
                "menu_border": "#2F6A64",
                "menu_selected_bg": "#266E67",
                "menu_selected_fg": "#FFFFFF",
                "header_bg": "#184C47",
                "header_fg": "#F2F7F4",
                "action_ribbon_bg": "#24534E",
                "action_ribbon_fg": "#FFF9E9",
                "action_ribbon_border": "#D8B35A",
                "tab_bg": "#173D39",
                "tab_fg": "#C6D8D2",
                "tab_border": "#2C5F59",
                "tab_hover_bg": "#215650",
                "tab_hover_fg": "#F2F7F4",
                "tab_hover_border": "#D8B35A",
                "tab_selected_bg": "#154440",
                "tab_selected_fg": "#FFF9E9",
                "tab_selected_border": "#D8B35A",
                "panel_radius": 10,
                "button_radius": 8,
                "help_button_radius": 6,
                "input_radius": 8,
                "table_radius": 8,
                "tab_radius": 10,
                "menu_radius": 10,
                "help_button_size": 11,
            }
        ),
    ),
    StarterThemeSpec(
        name="Subconscious Cosmos",
        description="A starfield-inspired navy theme drawn from the Tales of the Subconscious artwork, blending cosmic blues with luminous cyan and warm highlights.",
        values=_theme(
            {
                "font_size": 10,
                "dialog_title_font_size": 14,
                "section_title_font_size": 12,
                "secondary_text_font_size": 9,
                "window_bg": "#0A1628",
                "window_fg": "#EAF3FF",
                "panel_bg": "#10213A",
                "panel_alt_bg": "#17304C",
                "border_color": "#294A67",
                "accent": "#5BC7FF",
                "selection_bg": "#173A60",
                "selection_fg": "#F5FBFF",
                "secondary_text": "#A9BED4",
                "hint_text": "#82A9D1",
                "link_color": "#8CE4FF",
                "tooltip_bg": "#11243E",
                "tooltip_fg": "#F5FBFF",
                "tooltip_border": "#355C7D",
                "overlay_bg": "#3A4961",
                "overlay_fg": "#F9FBFF",
                "button_bg": "#173457",
                "button_fg": "#F5FBFF",
                "button_border": "#2E5B8B",
                "button_hover_bg": "#1E4573",
                "button_hover_fg": "#FFFFFF",
                "button_hover_border": "#5BC7FF",
                "button_pressed_bg": "#5BC7FF",
                "button_pressed_fg": "#0C1628",
                "button_pressed_border": "#9FE7FF",
                "button_disabled_bg": "#13253D",
                "button_disabled_fg": "#73859B",
                "button_disabled_border": "#2B4259",
                "help_button_bg": "#F0B35C",
                "help_button_fg": "#182031",
                "help_button_border": "#F7D088",
                "help_button_hover_bg": "#F5C877",
                "help_button_hover_fg": "#182031",
                "help_button_hover_border": "#FFE1AE",
                "help_button_pressed_bg": "#D28C32",
                "help_button_pressed_fg": "#FFF8E9",
                "help_button_pressed_border": "#F0B35C",
                "input_bg": "#0F2440",
                "input_fg": "#EAF3FF",
                "input_border": "#335E88",
                "input_focus_bg": "#14304F",
                "input_focus_fg": "#FFFFFF",
                "input_focus_border": "#5BC7FF",
                "input_disabled_bg": "#112034",
                "input_disabled_fg": "#7C90A6",
                "input_disabled_border": "#2C425D",
                "placeholder_fg": "#8097B1",
                "indicator_bg": "#11243E",
                "indicator_border": "#7EA9CF",
                "indicator_checked_bg": "#5BC7FF",
                "indicator_checked_border": "#9FE7FF",
                "table_bg": "#0C1D33",
                "table_fg": "#EAF3FF",
                "table_alt_bg": "#102640",
                "table_border": "#294A67",
                "table_grid": "#1B344D",
                "table_hover_bg": "#173457",
                "scrollbar_bg": "#11243E",
                "scrollbar_handle_bg": "#2D5B85",
                "scrollbar_handle_hover_bg": "#4176A6",
                "progress_bg": "#183250",
                "progress_chunk_bg": "#F0B35C",
                "menu_bg": "#10213A",
                "menu_fg": "#F5FBFF",
                "menu_border": "#294A67",
                "menu_selected_bg": "#173A60",
                "menu_selected_fg": "#FFFFFF",
                "header_bg": "#14304B",
                "header_fg": "#F5FBFF",
                "action_ribbon_bg": "#12395F",
                "action_ribbon_fg": "#F5FBFF",
                "action_ribbon_border": "#5BC7FF",
                "tab_bg": "#102542",
                "tab_fg": "#C1D5EA",
                "tab_border": "#294A67",
                "tab_hover_bg": "#163558",
                "tab_hover_fg": "#FFFFFF",
                "tab_hover_border": "#5BC7FF",
                "tab_selected_bg": "#173A60",
                "tab_selected_fg": "#F5FBFF",
                "tab_selected_border": "#5BC7FF",
                "panel_radius": 10,
                "button_radius": 8,
                "help_button_radius": 6,
                "input_radius": 8,
                "table_radius": 8,
                "tab_radius": 10,
                "menu_radius": 10,
                "help_button_size": 11,
            }
        ),
    ),
    StarterThemeSpec(
        name="VS Code Dark",
        description="A workhorse developer theme inspired by the Visual Studio Code dark interface.",
        values=_theme(
            {
                "font_size": 10,
                "dialog_title_font_size": 14,
                "section_title_font_size": 12,
                "secondary_text_font_size": 9,
                "window_bg": "#1E1E1E",
                "window_fg": "#D4D4D4",
                "panel_bg": "#252526",
                "panel_alt_bg": "#2D2D30",
                "border_color": "#3C3C3C",
                "accent": "#007ACC",
                "selection_bg": "#264F78",
                "selection_fg": "#FFFFFF",
                "secondary_text": "#9DA1A6",
                "hint_text": "#808080",
                "link_color": "#4FC1FF",
                "tooltip_bg": "#252526",
                "tooltip_fg": "#D4D4D4",
                "tooltip_border": "#3C3C3C",
                "overlay_bg": "#3B3F45",
                "overlay_fg": "#F3F4F6",
                "button_bg": "#0E639C",
                "button_fg": "#FFFFFF",
                "button_border": "#1177BB",
                "button_hover_bg": "#1177BB",
                "button_hover_fg": "#FFFFFF",
                "button_hover_border": "#3794FF",
                "button_pressed_bg": "#005A9E",
                "button_pressed_fg": "#FFFFFF",
                "button_pressed_border": "#3794FF",
                "button_disabled_bg": "#2D2D30",
                "button_disabled_fg": "#7F848E",
                "button_disabled_border": "#3C3C3C",
                "help_button_bg": "#007ACC",
                "help_button_fg": "#FFFFFF",
                "help_button_border": "#3794FF",
                "input_bg": "#1F1F1F",
                "input_fg": "#D4D4D4",
                "input_border": "#3C3C3C",
                "input_focus_bg": "#252526",
                "input_focus_fg": "#FFFFFF",
                "input_focus_border": "#007ACC",
                "input_disabled_bg": "#252526",
                "input_disabled_fg": "#7F848E",
                "input_disabled_border": "#3C3C3C",
                "placeholder_fg": "#808080",
                "indicator_bg": "#252526",
                "indicator_border": "#7F848E",
                "indicator_checked_bg": "#007ACC",
                "indicator_checked_border": "#3794FF",
                "table_bg": "#1E1E1E",
                "table_fg": "#D4D4D4",
                "table_alt_bg": "#252526",
                "table_border": "#3C3C3C",
                "table_grid": "#2D2D30",
                "table_hover_bg": "#2A2D2E",
                "scrollbar_bg": "#252526",
                "scrollbar_handle_bg": "#4D4D4D",
                "scrollbar_handle_hover_bg": "#5A5A5A",
                "progress_bg": "#2D2D30",
                "progress_chunk_bg": "#0E70C0",
                "menu_bg": "#252526",
                "menu_fg": "#D4D4D4",
                "menu_border": "#3C3C3C",
                "menu_selected_bg": "#094771",
                "menu_selected_fg": "#FFFFFF",
                "header_bg": "#2D2D30",
                "header_fg": "#D4D4D4",
                "action_ribbon_bg": "#094771",
                "action_ribbon_fg": "#FFFFFF",
                "action_ribbon_border": "#3794FF",
                "tab_bg": "#2D2D30",
                "tab_fg": "#C5C5C5",
                "tab_border": "#3C3C3C",
                "tab_hover_bg": "#333337",
                "tab_hover_fg": "#FFFFFF",
                "tab_hover_border": "#4B4B4F",
                "tab_selected_bg": "#1E1E1E",
                "tab_selected_fg": "#FFFFFF",
                "tab_selected_border": "#007ACC",
                "panel_radius": 7,
                "button_radius": 6,
                "help_button_radius": 6,
                "input_radius": 6,
                "table_radius": 6,
                "tab_radius": 8,
                "menu_radius": 6,
                "help_button_size": 11,
            }
        ),
    ),
    StarterThemeSpec(
        name="Pastel Studio",
        description="A soft pastel workspace with airy surfaces, mint accents, and readable warm-neutral text.",
        values=_theme(
            {
                "font_size": 10,
                "dialog_title_font_size": 14,
                "section_title_font_size": 12,
                "secondary_text_font_size": 9,
                "window_bg": "#FFF8F2",
                "window_fg": "#3F3943",
                "panel_bg": "#FFFFFF",
                "panel_alt_bg": "#F6EEE8",
                "border_color": "#D8C9C0",
                "accent": "#81C7BE",
                "selection_bg": "#D7F0EC",
                "selection_fg": "#2F3438",
                "secondary_text": "#7A6F7D",
                "hint_text": "#9A8FA0",
                "link_color": "#6FA8DC",
                "tooltip_bg": "#FFFDFB",
                "tooltip_fg": "#3F3943",
                "tooltip_border": "#D8C9C0",
                "overlay_bg": "#EBDAD1",
                "overlay_fg": "#3F3943",
                "button_bg": "#F7D8D3",
                "button_fg": "#4B3C44",
                "button_border": "#D6B4AD",
                "button_hover_bg": "#F3C9C1",
                "button_hover_fg": "#4B3C44",
                "button_hover_border": "#81C7BE",
                "button_pressed_bg": "#81C7BE",
                "button_pressed_fg": "#223133",
                "button_pressed_border": "#5DA89F",
                "button_disabled_bg": "#F2E9E3",
                "button_disabled_fg": "#A08E97",
                "button_disabled_border": "#D8C9C0",
                "help_button_bg": "#81C7BE",
                "help_button_fg": "#223133",
                "help_button_border": "#5DA89F",
                "help_button_hover_bg": "#98D8CF",
                "help_button_hover_fg": "#223133",
                "help_button_hover_border": "#6FBEB4",
                "help_button_pressed_bg": "#67B6AC",
                "help_button_pressed_fg": "#FFFFFF",
                "help_button_pressed_border": "#4E988F",
                "input_bg": "#FFFDFC",
                "input_fg": "#3F3943",
                "input_border": "#D8C9C0",
                "input_focus_bg": "#FFFFFF",
                "input_focus_fg": "#3F3943",
                "input_focus_border": "#81C7BE",
                "input_disabled_bg": "#F6F1EC",
                "input_disabled_fg": "#A08E97",
                "input_disabled_border": "#D8C9C0",
                "placeholder_fg": "#A796A2",
                "indicator_bg": "#FFFFFF",
                "indicator_border": "#C8B8AF",
                "indicator_checked_bg": "#81C7BE",
                "indicator_checked_border": "#5DA89F",
                "table_bg": "#FFFFFF",
                "table_fg": "#3F3943",
                "table_alt_bg": "#FCF6F1",
                "table_border": "#D8C9C0",
                "table_grid": "#EEE1D8",
                "table_hover_bg": "#FCEEE8",
                "scrollbar_bg": "#F4E9E2",
                "scrollbar_handle_bg": "#D9C0B7",
                "scrollbar_handle_hover_bg": "#C9A89F",
                "progress_bg": "#F0E5DE",
                "progress_chunk_bg": "#81C7BE",
                "menu_bg": "#FFF8F2",
                "menu_fg": "#3F3943",
                "menu_border": "#D8C9C0",
                "menu_selected_bg": "#D7F0EC",
                "menu_selected_fg": "#2F3438",
                "header_bg": "#F0E3DA",
                "header_fg": "#4B3C44",
                "action_ribbon_bg": "#DFF3EE",
                "action_ribbon_fg": "#314245",
                "action_ribbon_border": "#81C7BE",
                "tab_bg": "#F5EAE2",
                "tab_fg": "#6F5E68",
                "tab_border": "#D8C9C0",
                "tab_hover_bg": "#F8F0EA",
                "tab_hover_fg": "#4B3C44",
                "tab_hover_border": "#CDBCB3",
                "tab_selected_bg": "#FFFFFF",
                "tab_selected_fg": "#4B3C44",
                "tab_selected_border": "#81C7BE",
                "panel_radius": 12,
                "button_radius": 10,
                "button_padding_v": 7,
                "button_padding_h": 14,
                "help_button_radius": 6,
                "input_radius": 10,
                "table_radius": 10,
                "tab_radius": 12,
                "menu_radius": 10,
                "help_button_size": 11,
            }
        ),
    ),
)


def starter_theme_names() -> tuple[str, ...]:
    return tuple(spec.name for spec in STARTER_THEME_SPECS)


def starter_theme_library() -> dict[str, dict[str, object]]:
    return {spec.name: dict(spec.values) for spec in STARTER_THEME_SPECS}


def starter_theme_descriptions() -> dict[str, str]:
    return {spec.name: spec.description for spec in STARTER_THEME_SPECS}
