"""ISO 4217 currency helpers for invoicing and accounting workflows."""

from __future__ import annotations

import re

ISO_4217_CURRENCY_CODES: tuple[str, ...] = (
    "AED",
    "AFN",
    "ALL",
    "AMD",
    "ANG",
    "AOA",
    "ARS",
    "AUD",
    "AWG",
    "AZN",
    "BAM",
    "BBD",
    "BDT",
    "BGN",
    "BHD",
    "BIF",
    "BMD",
    "BND",
    "BOB",
    "BOV",
    "BRL",
    "BSD",
    "BTN",
    "BWP",
    "BYN",
    "BZD",
    "CAD",
    "CDF",
    "CHE",
    "CHF",
    "CHW",
    "CLF",
    "CLP",
    "CNY",
    "COP",
    "COU",
    "CRC",
    "CUC",
    "CUP",
    "CVE",
    "CZK",
    "DJF",
    "DKK",
    "DOP",
    "DZD",
    "EGP",
    "ERN",
    "ETB",
    "EUR",
    "FJD",
    "FKP",
    "GBP",
    "GEL",
    "GHS",
    "GIP",
    "GMD",
    "GNF",
    "GTQ",
    "GYD",
    "HKD",
    "HNL",
    "HTG",
    "HUF",
    "IDR",
    "ILS",
    "INR",
    "IQD",
    "IRR",
    "ISK",
    "JMD",
    "JOD",
    "JPY",
    "KES",
    "KGS",
    "KHR",
    "KMF",
    "KPW",
    "KRW",
    "KWD",
    "KYD",
    "KZT",
    "LAK",
    "LBP",
    "LKR",
    "LRD",
    "LSL",
    "LYD",
    "MAD",
    "MDL",
    "MGA",
    "MKD",
    "MMK",
    "MNT",
    "MOP",
    "MRU",
    "MUR",
    "MVR",
    "MWK",
    "MXN",
    "MXV",
    "MYR",
    "MZN",
    "NAD",
    "NGN",
    "NIO",
    "NOK",
    "NPR",
    "NZD",
    "OMR",
    "PAB",
    "PEN",
    "PGK",
    "PHP",
    "PKR",
    "PLN",
    "PYG",
    "QAR",
    "RON",
    "RSD",
    "RUB",
    "RWF",
    "SAR",
    "SBD",
    "SCR",
    "SDG",
    "SEK",
    "SGD",
    "SHP",
    "SLE",
    "SLL",
    "SOS",
    "SRD",
    "SSP",
    "STN",
    "SVC",
    "SYP",
    "SZL",
    "THB",
    "TJS",
    "TMT",
    "TND",
    "TOP",
    "TRY",
    "TTD",
    "TWD",
    "TZS",
    "UAH",
    "UGX",
    "USD",
    "USN",
    "UYI",
    "UYU",
    "UYW",
    "UZS",
    "VED",
    "VES",
    "VND",
    "VUV",
    "WST",
    "XAF",
    "XAG",
    "XAU",
    "XBA",
    "XBB",
    "XBC",
    "XBD",
    "XCD",
    "XCG",
    "XDR",
    "XOF",
    "XPD",
    "XPF",
    "XPT",
    "XSU",
    "XTS",
    "XUA",
    "XXX",
    "YER",
    "ZAR",
    "ZMW",
    "ZWG",
    "ZWL",
)

_ISO_4217_CURRENCY_CODE_SET = frozenset(ISO_4217_CURRENCY_CODES)
_COUNTRY_KEY_RE = re.compile(r"[^A-Z0-9]+")

_EURO_COUNTRY_KEYS = frozenset(
    {
        "AD",
        "AT",
        "AX",
        "BE",
        "CY",
        "DE",
        "EE",
        "ES",
        "FI",
        "FR",
        "GF",
        "GP",
        "GR",
        "HR",
        "IE",
        "IT",
        "LT",
        "LU",
        "LV",
        "MC",
        "ME",
        "MF",
        "MQ",
        "MT",
        "NL",
        "PM",
        "PT",
        "RE",
        "SI",
        "SK",
        "SM",
        "TF",
        "VA",
        "YT",
    }
)

_COUNTRY_CURRENCY_OVERRIDES = {
    "AU": "AUD",
    "BR": "BRL",
    "CA": "CAD",
    "CH": "CHF",
    "CN": "CNY",
    "DK": "DKK",
    "GB": "GBP",
    "HK": "HKD",
    "JP": "JPY",
    "MX": "MXN",
    "NO": "NOK",
    "NZ": "NZD",
    "SE": "SEK",
    "SG": "SGD",
    "US": "USD",
    "ZA": "ZAR",
    "AUSTRALIA": "AUD",
    "BRAZIL": "BRL",
    "CANADA": "CAD",
    "CHINA": "CNY",
    "DENMARK": "DKK",
    "GREATBRITAIN": "GBP",
    "HONGKONG": "HKD",
    "JAPAN": "JPY",
    "MEXICO": "MXN",
    "NEWZEALAND": "NZD",
    "NORWAY": "NOK",
    "SINGAPORE": "SGD",
    "SOUTHAFRICA": "ZAR",
    "SWEDEN": "SEK",
    "SWITZERLAND": "CHF",
    "THEUNITEDKINGDOM": "GBP",
    "UNITEDKINGDOM": "GBP",
    "UNITEDSTATES": "USD",
    "UNITEDSTATESOFAMERICA": "USD",
    "USA": "USD",
}

_EURO_COUNTRY_NAME_KEYS = frozenset(
    {
        "ANDORRA",
        "AUSTRIA",
        "BELGIUM",
        "CROATIA",
        "CYPRUS",
        "ESTONIA",
        "FINLAND",
        "FRANCE",
        "GERMANY",
        "GREECE",
        "IRELAND",
        "ITALY",
        "LATVIA",
        "LITHUANIA",
        "LUXEMBOURG",
        "MALTA",
        "MONACO",
        "MONTENEGRO",
        "NETHERLANDS",
        "PORTUGAL",
        "SANMARINO",
        "SLOVAKIA",
        "SLOVENIA",
        "SPAIN",
        "THENETHERLANDS",
        "VATICANCITY",
    }
)


def is_iso_4217_currency_code(value: object | None) -> bool:
    return str(value or "").strip().upper() in _ISO_4217_CURRENCY_CODE_SET


def currency_for_country(value: object | None) -> str | None:
    clean = _COUNTRY_KEY_RE.sub("", str(value or "").strip().upper())
    if not clean:
        return None
    if clean in _EURO_COUNTRY_KEYS or clean in _EURO_COUNTRY_NAME_KEYS:
        return "EUR"
    return _COUNTRY_CURRENCY_OVERRIDES.get(clean)
