"""Host protocols for album and track editor dialogs."""

from __future__ import annotations

from typing import Any, Protocol


class AlbumEditorHost(Protocol):
    conn: Any
    cursor: Any
    logger: Any
    track_service: Any
    work_service: Any

    def _activate_isrc_claim_for_track(self, *args: Any, **kwargs: Any) -> Any: ...
    def _advance_task_ui_progress(self, *args: Any, **kwargs: Any) -> Any: ...
    def _apply_catalog_refresh_request(self, *args: Any, **kwargs: Any) -> Any: ...
    def _audit(self, *args: Any, **kwargs: Any) -> Any: ...
    def _audit_commit(self, *args: Any, **kwargs: Any) -> Any: ...
    def _capture_catalog_refresh_request(self, *args: Any, **kwargs: Any) -> Any: ...
    def _choose_media_into_line_edit(self, *args: Any, **kwargs: Any) -> Any: ...
    def _choose_track_media_storage_modes(self, *args: Any, **kwargs: Any) -> Any: ...
    def _configure_artist_party_combo(self, *args: Any, **kwargs: Any) -> Any: ...
    def _confirm_lossy_primary_audio_selection(self, *args: Any, **kwargs: Any) -> Any: ...
    def _current_profile_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def _focus_work_in_manager(self, *args: Any, **kwargs: Any) -> Any: ...
    def _get_track_title(self, *args: Any, **kwargs: Any) -> Any: ...
    def _isrc_generation_state(self, *args: Any, **kwargs: Any) -> Any: ...
    def _load_catalog_ui_dataset_from_bundle(self, *args: Any, **kwargs: Any) -> Any: ...
    def _log_event(self, *args: Any, **kwargs: Any) -> Any: ...
    def _next_generated_isrc(self, *args: Any, **kwargs: Any) -> Any: ...
    def _normalize_work_track_relationship(self, *args: Any, **kwargs: Any) -> Any: ...
    def _parse_additional_artists(self, *args: Any, **kwargs: Any) -> Any: ...
    def _refresh_line_edit_lossy_audio_warning(self, *args: Any, **kwargs: Any) -> Any: ...
    def _refresh_work_manager_panel(self, *args: Any, **kwargs: Any) -> Any: ...
    def _release_reserved_isrc_claim(self, *args: Any, **kwargs: Any) -> Any: ...
    def _reserve_isrc_claim_for_profile(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_artist_party_choice(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_party_backed_additional_artist_names(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_party_backed_artist_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def _scaled_progress_callback(self, *args: Any, **kwargs: Any) -> Any: ...
    def _scaled_ui_progress_callback(self, *args: Any, **kwargs: Any) -> Any: ...
    def _show_background_task_error(self, *args: Any, **kwargs: Any) -> Any: ...
    def _submit_background_bundle_task(self, *args: Any, **kwargs: Any) -> Any: ...
    def _sync_releases_for_tracks(self, *args: Any, **kwargs: Any) -> Any: ...
    def _warn_duplicate_track_numbers(self, *args: Any, **kwargs: Any) -> Any: ...
    def _work_track_relationship_choices(self, *args: Any, **kwargs: Any) -> Any: ...
    def _work_track_relationship_label(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_isrc_taken_normalized(self, *args: Any, **kwargs: Any) -> Any: ...
    def statusBar(self, *args: Any, **kwargs: Any) -> Any: ...


class TrackEditorHost(Protocol):
    code_registry_service: Any
    conn: Any
    cursor: Any
    logger: Any
    party_service: Any
    track_service: Any
    work_service: Any

    def _advance_task_ui_progress(self, *args: Any, **kwargs: Any) -> Any: ...
    def _apply_audio_duration_to_widgets(self, *args: Any, **kwargs: Any) -> Any: ...
    def _apply_catalog_refresh_request(self, *args: Any, **kwargs: Any) -> Any: ...
    def _artist_lookup_values(self, *args: Any, **kwargs: Any) -> Any: ...
    def _artist_party_primary_label(self, *args: Any, **kwargs: Any) -> Any: ...
    def _browse_track_media_file(self, *args: Any, **kwargs: Any) -> Any: ...
    def _audit(self, *args: Any, **kwargs: Any) -> Any: ...
    def _audit_commit(self, *args: Any, **kwargs: Any) -> Any: ...
    def _capture_catalog_refresh_request(self, *args: Any, **kwargs: Any) -> Any: ...
    def _choose_track_media_storage_modes(self, *args: Any, **kwargs: Any) -> Any: ...
    def _collect_catalog_cleanup_targets(self, *args: Any, **kwargs: Any) -> Any: ...
    def _confirm_lossy_primary_audio_selection(self, *args: Any, **kwargs: Any) -> Any: ...
    def _current_profile_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def _load_catalog_ui_dataset_from_bundle(self, *args: Any, **kwargs: Any) -> Any: ...
    def _log_event(self, *args: Any, **kwargs: Any) -> Any: ...
    def _parse_additional_artists(self, *args: Any, **kwargs: Any) -> Any: ...
    def _refresh_line_edit_lossy_audio_warning(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_artist_party_choice(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_party_backed_additional_artist_names(self, *args: Any, **kwargs: Any) -> Any: ...
    def _resolve_party_backed_artist_name(self, *args: Any, **kwargs: Any) -> Any: ...
    def _scaled_ui_progress_callback(self, *args: Any, **kwargs: Any) -> Any: ...
    def _set_track_length_widgets(self, *args: Any, **kwargs: Any) -> Any: ...
    def _show_background_task_error(self, *args: Any, **kwargs: Any) -> Any: ...
    def _submit_background_bundle_task(self, *args: Any, **kwargs: Any) -> Any: ...
    def _sync_application_isrc_registry(self, *args: Any, **kwargs: Any) -> Any: ...
    def _sync_releases_for_tracks(self, *args: Any, **kwargs: Any) -> Any: ...
    def _warn_duplicate_track_numbers(self, *args: Any, **kwargs: Any) -> Any: ...
    def is_isrc_taken_normalized(self, *args: Any, **kwargs: Any) -> Any: ...
    def open_track_editor(self, *args: Any, **kwargs: Any) -> Any: ...
    def refresh_table_preserve_view(self, *args: Any, **kwargs: Any) -> Any: ...
    def statusBar(self, *args: Any, **kwargs: Any) -> Any: ...


__all__ = ["AlbumEditorHost", "TrackEditorHost"]
