"""Central code-registry domain exports."""

from .models import (
    BUILTIN_CATEGORY_CATALOG_NUMBER,
    BUILTIN_CATEGORY_CONTRACT_NUMBER,
    BUILTIN_CATEGORY_LICENSE_NUMBER,
    BUILTIN_CATEGORY_REGISTRY_SHA256_KEY,
    CATALOG_MODE_EMPTY,
    CATALOG_MODE_EXTERNAL,
    CATALOG_MODE_INTERNAL,
    CLASSIFICATION_CANONICAL_CANDIDATE,
    CLASSIFICATION_EXTERNAL,
    CLASSIFICATION_INTERNAL,
    CLASSIFICATION_MISMATCH,
    ENTRY_KIND_GENERATED,
    ENTRY_KIND_IMPORTED,
    ENTRY_KIND_MANUAL_CAPTURE,
    ENTRY_KIND_SHA256_GENERATED,
    GENERATION_STRATEGY_MANUAL,
    GENERATION_STRATEGY_SEQUENTIAL,
    GENERATION_STRATEGY_SHA256,
    SUBJECT_KIND_CATALOG,
    SUBJECT_KIND_CONTRACT,
    SUBJECT_KIND_GENERIC,
    SUBJECT_KIND_KEY,
    SUBJECT_KIND_LICENSE,
    CatalogIdentifierClassification,
    CatalogIdentifierResolution,
    CodeRegistryAssignmentTarget,
    CodeRegistryCategoryPayload,
    CodeRegistryCategoryRecord,
    CodeRegistryChoice,
    CodeRegistryEntryGenerationResult,
    CodeRegistryEntryRecord,
    CodeRegistryUsageLink,
    ExternalCatalogIdentifierRecord,
)
from .service import CodeRegistryService
from .widgets import CatalogIdentifierField, CatalogIdentifierSelector
from .workspace import CodeRegistryWorkspacePanel

__all__ = [
    "BUILTIN_CATEGORY_CATALOG_NUMBER",
    "BUILTIN_CATEGORY_CONTRACT_NUMBER",
    "BUILTIN_CATEGORY_LICENSE_NUMBER",
    "BUILTIN_CATEGORY_REGISTRY_SHA256_KEY",
    "CATALOG_MODE_EMPTY",
    "CATALOG_MODE_EXTERNAL",
    "CATALOG_MODE_INTERNAL",
    "CLASSIFICATION_CANONICAL_CANDIDATE",
    "CLASSIFICATION_EXTERNAL",
    "CLASSIFICATION_INTERNAL",
    "CLASSIFICATION_MISMATCH",
    "ENTRY_KIND_GENERATED",
    "ENTRY_KIND_IMPORTED",
    "ENTRY_KIND_MANUAL_CAPTURE",
    "ENTRY_KIND_SHA256_GENERATED",
    "GENERATION_STRATEGY_MANUAL",
    "GENERATION_STRATEGY_SEQUENTIAL",
    "GENERATION_STRATEGY_SHA256",
    "SUBJECT_KIND_CATALOG",
    "SUBJECT_KIND_CONTRACT",
    "SUBJECT_KIND_GENERIC",
    "SUBJECT_KIND_KEY",
    "SUBJECT_KIND_LICENSE",
    "CatalogIdentifierClassification",
    "CatalogIdentifierResolution",
    "CatalogIdentifierField",
    "CatalogIdentifierSelector",
    "CodeRegistryAssignmentTarget",
    "CodeRegistryCategoryPayload",
    "CodeRegistryCategoryRecord",
    "CodeRegistryChoice",
    "CodeRegistryEntryGenerationResult",
    "CodeRegistryEntryRecord",
    "CodeRegistryService",
    "CodeRegistryWorkspacePanel",
    "CodeRegistryUsageLink",
    "ExternalCatalogIdentifierRecord",
]
