"""Service-layer mutation entrypoints."""

from isrc_manager.assets import (
    ASSET_TYPE_CHOICES,
    AssetService,
    AssetValidationIssue,
    AssetVersionPayload,
    AssetVersionRecord,
)
from isrc_manager.contracts import (
    CONTRACT_STATUS_CHOICES,
    DOCUMENT_TYPE_CHOICES,
    OBLIGATION_TYPE_CHOICES,
    ContractDeadline,
    ContractDetail,
    ContractDocumentPayload,
    ContractDocumentRecord,
    ContractObligationPayload,
    ContractObligationRecord,
    ContractPartyPayload,
    ContractPartyRecord,
    ContractPayload,
    ContractRecord,
    ContractService,
    ContractValidationIssue,
)
from isrc_manager.contract_templates import (
    ContractTemplateCatalogEntry,
    ContractTemplateCatalogSection,
    ContractTemplateCatalogService,
    ContractTemplateDraftPayload,
    ContractTemplateDraftRecord,
    ContractTemplateFormChoice,
    ContractTemplateFormDefinition,
    ContractTemplateFormManualField,
    ContractTemplateFormSelectorField,
    ContractTemplateFormService,
    ContractTemplateImportResult,
    ContractTemplateIngestionError,
    ContractTemplateOutputArtifactPayload,
    ContractTemplateOutputArtifactRecord,
    ContractTemplatePayload,
    ContractTemplatePlaceholderBindingPayload,
    ContractTemplatePlaceholderBindingRecord,
    ContractTemplatePlaceholderPayload,
    ContractTemplatePlaceholderRecord,
    ContractTemplateResolvedSnapshotPayload,
    ContractTemplateResolvedSnapshotRecord,
    ContractTemplateRevisionPayload,
    ContractTemplateRevisionRecord,
    ContractTemplateRecord,
    ContractTemplateScanDiagnostic,
    ContractTemplateScanEntry,
    ContractTemplateScanOccurrence,
    ContractTemplateScanResult,
    ContractTemplateService,
    DOCXTemplateScanner,
    InvalidPlaceholderError,
    PagesTemplateAdapter,
    PlaceholderOccurrence,
    PlaceholderToken,
    SUPPORTED_TEMPLATE_SOURCE_FORMATS,
    dedupe_placeholders,
    detect_template_source_format,
    extract_placeholders,
    parse_placeholder,
)
from isrc_manager.parties import (
    PARTY_TYPE_CHOICES,
    PartyDuplicate,
    PartyPayload,
    PartyRecord,
    PartyService,
    PartyUsageSummary,
)
from isrc_manager.releases import (
    RELEASE_TYPE_CHOICES,
    ReleasePayload,
    ReleaseRecord,
    ReleaseService,
    ReleaseSummary,
    ReleaseTrackPlacement,
    ReleaseValidationIssue,
)
from isrc_manager.rights import (
    RIGHT_TYPE_CHOICES,
    OwnershipSummary,
    RightPayload,
    RightRecord,
    RightsConflict,
    RightsService,
)
from isrc_manager.works import (
    WORK_CREATOR_ROLE_CHOICES,
    WORK_STATUS_CHOICES,
    WorkContributorPayload,
    WorkContributorRecord,
    WorkDetail,
    WorkPayload,
    WorkRecord,
    WorkService,
    WorkValidationIssue,
)

from .catalog_admin import AlbumUsage, ArtistUsage, CatalogAdminService, LicenseeUsage
from .catalog_reads import CatalogReadService
from .custom_fields import (
    CustomFieldDefinitionService,
    CustomFieldValueService,
    LegacyPromotedFieldRepairCandidate,
    LegacyPromotedFieldRepairResult,
    LegacyPromotedFieldRepairService,
)
from .database_admin import (
    BackupResult,
    DatabaseMaintenanceService,
    ProfileStoreService,
    RestoreResult,
)
from .exports import XMLExportService
from .gs1_contracts import GS1ContractImportService
from .gs1_excel import GS1ExcelExportService
from .gs1_integration import GS1IntegrationService
from .gs1_models import (
    GS1BatchValidationError,
    GS1ContractEntry,
    GS1ContractImportError,
    GS1DependencyError,
    GS1Error,
    GS1ExportPlan,
    GS1ExportPreview,
    GS1ExportResult,
    GS1MetadataGroup,
    GS1MetadataRecord,
    GS1PreparedRecord,
    GS1ProfileDefaults,
    GS1RecordContext,
    GS1TemplateAsset,
    GS1TemplateProfile,
    GS1TemplateSheetProfile,
    GS1TemplateVerificationError,
    GS1ValidationError,
    GS1ValidationIssue,
    GS1ValidationResult,
)
from .gs1_repository import GS1MetadataRepository
from .gs1_settings import GS1SettingsService
from .gs1_template import GS1TemplateVerificationService
from .gs1_validation import GS1ValidationService
from .imports import ImportExecutionResult, ImportInspection, ImportRecord, XMLImportService
from .license_migration import (
    LegacyLicenseMigrationIssue,
    LegacyLicenseMigrationResult,
    LegacyLicenseMigrationService,
    LegacyLicenseMigrationSummary,
)
from .licenses import LicenseRecord, LicenseRow, LicenseService
from .profiles import ProfileChoice, ProfileRemovalResult, ProfileWorkflowService
from .repertoire_status import REPERTOIRE_STATUS_CHOICES, RepertoireWorkflowService
from .schema import DatabaseSchemaService
from .session import DatabaseSessionService, OpenDatabaseSession, ProfileKVService
from .settings_mutations import SettingsMutationService
from .settings_reads import (
    AutoSnapshotSettings,
    HistoryRetentionSettings,
    RegistrationSettings,
    SettingsReadService,
)
from .tracks import (
    TrackCreatePayload,
    TrackMediaSourceHandle,
    TrackService,
    TrackSnapshot,
    TrackUpdatePayload,
)

__all__ = [
    "AlbumUsage",
    "ASSET_TYPE_CHOICES",
    "ArtistUsage",
    "AutoSnapshotSettings",
    "BackupResult",
    "CatalogAdminService",
    "CatalogReadService",
    "CONTRACT_STATUS_CHOICES",
    "CustomFieldDefinitionService",
    "CustomFieldValueService",
    "DatabaseMaintenanceService",
    "DatabaseSchemaService",
    "DatabaseSessionService",
    "DOCUMENT_TYPE_CHOICES",
    "GS1BatchValidationError",
    "GS1ContractEntry",
    "GS1ContractImportError",
    "GS1ContractImportService",
    "GS1DependencyError",
    "GS1Error",
    "GS1ExcelExportService",
    "GS1ExportPlan",
    "GS1ExportPreview",
    "GS1ExportResult",
    "GS1IntegrationService",
    "GS1MetadataGroup",
    "GS1MetadataRecord",
    "GS1MetadataRepository",
    "GS1PreparedRecord",
    "GS1ProfileDefaults",
    "GS1RecordContext",
    "GS1SettingsService",
    "GS1TemplateAsset",
    "GS1TemplateProfile",
    "GS1TemplateSheetProfile",
    "GS1TemplateVerificationError",
    "GS1TemplateVerificationService",
    "GS1ValidationError",
    "GS1ValidationIssue",
    "GS1ValidationResult",
    "GS1ValidationService",
    "HistoryRetentionSettings",
    "XMLExportService",
    "ImportExecutionResult",
    "ImportInspection",
    "ImportRecord",
    "OBLIGATION_TYPE_CHOICES",
    "OwnershipSummary",
    "PARTY_TYPE_CHOICES",
    "PartyDuplicate",
    "PartyPayload",
    "PartyRecord",
    "PartyService",
    "PartyUsageSummary",
    "LicenseeUsage",
    "LegacyLicenseMigrationIssue",
    "LegacyLicenseMigrationResult",
    "LegacyLicenseMigrationService",
    "LegacyLicenseMigrationSummary",
    "LegacyPromotedFieldRepairCandidate",
    "LegacyPromotedFieldRepairResult",
    "LegacyPromotedFieldRepairService",
    "LicenseRecord",
    "LicenseRow",
    "LicenseService",
    "OpenDatabaseSession",
    "ProfileChoice",
    "ProfileKVService",
    "ProfileRemovalResult",
    "ProfileStoreService",
    "ProfileWorkflowService",
    "REPERTOIRE_STATUS_CHOICES",
    "RELEASE_TYPE_CHOICES",
    "RIGHT_TYPE_CHOICES",
    "RegistrationSettings",
    "ReleasePayload",
    "ReleaseRecord",
    "ReleaseService",
    "ReleaseSummary",
    "ReleaseTrackPlacement",
    "ReleaseValidationIssue",
    "RepertoireWorkflowService",
    "RightPayload",
    "RightRecord",
    "RightsConflict",
    "RightsService",
    "RestoreResult",
    "SettingsReadService",
    "SettingsMutationService",
    "TrackCreatePayload",
    "TrackMediaSourceHandle",
    "TrackService",
    "TrackSnapshot",
    "TrackUpdatePayload",
    "WORK_CREATOR_ROLE_CHOICES",
    "WORK_STATUS_CHOICES",
    "WorkContributorPayload",
    "WorkContributorRecord",
    "WorkDetail",
    "WorkPayload",
    "WorkRecord",
    "WorkService",
    "WorkValidationIssue",
    "AssetService",
    "AssetValidationIssue",
    "AssetVersionPayload",
    "AssetVersionRecord",
    "ContractDeadline",
    "ContractDetail",
    "ContractDocumentPayload",
    "ContractDocumentRecord",
    "ContractObligationPayload",
    "ContractObligationRecord",
    "ContractPartyPayload",
    "ContractPartyRecord",
    "ContractPayload",
    "ContractRecord",
    "ContractService",
    "ContractTemplateCatalogEntry",
    "ContractTemplateCatalogSection",
    "ContractTemplateCatalogService",
    "ContractTemplateDraftPayload",
    "ContractTemplateDraftRecord",
    "ContractTemplateFormChoice",
    "ContractTemplateFormDefinition",
    "ContractTemplateFormManualField",
    "ContractTemplateFormSelectorField",
    "ContractTemplateFormService",
    "ContractTemplateImportResult",
    "ContractTemplateIngestionError",
    "ContractTemplateOutputArtifactPayload",
    "ContractTemplateOutputArtifactRecord",
    "ContractTemplatePayload",
    "ContractTemplatePlaceholderBindingPayload",
    "ContractTemplatePlaceholderBindingRecord",
    "ContractTemplatePlaceholderPayload",
    "ContractTemplatePlaceholderRecord",
    "ContractTemplateResolvedSnapshotPayload",
    "ContractTemplateResolvedSnapshotRecord",
    "ContractTemplateRevisionPayload",
    "ContractTemplateRevisionRecord",
    "ContractTemplateRecord",
    "ContractTemplateScanDiagnostic",
    "ContractTemplateScanEntry",
    "ContractTemplateScanOccurrence",
    "ContractTemplateScanResult",
    "ContractTemplateService",
    "DOCXTemplateScanner",
    "ContractValidationIssue",
    "dedupe_placeholders",
    "extract_placeholders",
    "InvalidPlaceholderError",
    "parse_placeholder",
    "PagesTemplateAdapter",
    "PlaceholderOccurrence",
    "PlaceholderToken",
    "SUPPORTED_TEMPLATE_SOURCE_FORMATS",
    "detect_template_source_format",
    "XMLImportService",
]
