"""Contract template placeholder workflow package."""

from .catalog import (
    ContractTemplateCatalogEntry,
    ContractTemplateCatalogSection,
    ContractTemplateCatalogService,
)
from .ingestion import (
    ContractTemplateIngestionError,
    DOCXTemplateScanner,
    PagesTemplateAdapter,
    SUPPORTED_TEMPLATE_SOURCE_FORMATS,
    detect_template_source_format,
)
from .models import (
    ContractTemplateImportResult,
    ContractTemplateDraftPayload,
    ContractTemplateDraftRecord,
    ContractTemplateOutputArtifactPayload,
    ContractTemplateOutputArtifactRecord,
    ContractTemplatePayload,
    ContractTemplatePlaceholderBindingPayload,
    ContractTemplatePlaceholderBindingRecord,
    ContractTemplatePlaceholderPayload,
    ContractTemplatePlaceholderRecord,
    ContractTemplateResolvedSnapshotPayload,
    ContractTemplateResolvedSnapshotRecord,
    ContractTemplateRevisionPayload,
    ContractTemplateRevisionRecord,
    ContractTemplateRecord,
    ContractTemplateScanDiagnostic,
    ContractTemplateScanEntry,
    ContractTemplateScanOccurrence,
    ContractTemplateScanResult,
)
from .parser import (
    InvalidPlaceholderError,
    PlaceholderOccurrence,
    PlaceholderToken,
    dedupe_placeholders,
    extract_placeholders,
    parse_placeholder,
)
from .service import ContractTemplateService

__all__ = [
    "ContractTemplateCatalogEntry",
    "ContractTemplateCatalogSection",
    "ContractTemplateCatalogService",
    "ContractTemplateDraftPayload",
    "ContractTemplateDraftRecord",
    "ContractTemplateImportResult",
    "ContractTemplateIngestionError",
    "ContractTemplateOutputArtifactPayload",
    "ContractTemplateOutputArtifactRecord",
    "ContractTemplatePayload",
    "ContractTemplatePlaceholderBindingPayload",
    "ContractTemplatePlaceholderBindingRecord",
    "ContractTemplatePlaceholderPayload",
    "ContractTemplatePlaceholderRecord",
    "ContractTemplateResolvedSnapshotPayload",
    "ContractTemplateResolvedSnapshotRecord",
    "ContractTemplateRevisionPayload",
    "ContractTemplateRevisionRecord",
    "ContractTemplateRecord",
    "ContractTemplateScanDiagnostic",
    "ContractTemplateScanEntry",
    "ContractTemplateScanOccurrence",
    "ContractTemplateScanResult",
    "ContractTemplateService",
    "DOCXTemplateScanner",
    "InvalidPlaceholderError",
    "PagesTemplateAdapter",
    "PlaceholderOccurrence",
    "PlaceholderToken",
    "SUPPORTED_TEMPLATE_SOURCE_FORMATS",
    "dedupe_placeholders",
    "detect_template_source_format",
    "extract_placeholders",
    "parse_placeholder",
]
