"""Contract template placeholder workflow package."""

from .catalog import (
    ContractTemplateCatalogEntry,
    ContractTemplateCatalogSection,
    ContractTemplateCatalogService,
)
from .errors import ContractTemplateIngestionError
from .export_service import (
    ContractTemplateExportError,
    ContractTemplateExportService,
    QtWebEngineHtmlPdfAdapter,
    TextutilDocxRenderAdapter,
)
from .form_service import ContractTemplateFormService
from .html_support import (
    HTMLTemplateBundle,
    HTMLTemplateBundleError,
    HTMLTemplateScanner,
)
from .ingestion import (
    SUPPORTED_TEMPLATE_SOURCE_FORMATS,
    DOCXTemplateScanner,
    PagesTemplateAdapter,
    detect_template_source_format,
)
from .models import (
    ContractTemplateDraftPayload,
    ContractTemplateDraftRecord,
    ContractTemplateDraftRegistryAssignmentRecord,
    ContractTemplateExportResult,
    ContractTemplateFormAutoField,
    ContractTemplateFormChoice,
    ContractTemplateFormDefinition,
    ContractTemplateFormManualField,
    ContractTemplateFormSelectorField,
    ContractTemplateImportResult,
    ContractTemplateOutputArtifactPayload,
    ContractTemplateOutputArtifactRecord,
    ContractTemplatePayload,
    ContractTemplatePlaceholderBindingPayload,
    ContractTemplatePlaceholderBindingRecord,
    ContractTemplatePlaceholderPayload,
    ContractTemplatePlaceholderRecord,
    ContractTemplateRecord,
    ContractTemplateResolvedSnapshotPayload,
    ContractTemplateResolvedSnapshotRecord,
    ContractTemplateRevisionAssetPayload,
    ContractTemplateRevisionAssetRecord,
    ContractTemplateRevisionPayload,
    ContractTemplateRevisionRecord,
    ContractTemplateScanDiagnostic,
    ContractTemplateScanEntry,
    ContractTemplateScanOccurrence,
    ContractTemplateScanResult,
    build_contract_template_indexed_selection_key,
)
from .parser import (
    InvalidPlaceholderError,
    PlaceholderOccurrence,
    PlaceholderToken,
    base_symbol_for_indexed_placeholder,
    dedupe_placeholders,
    extract_placeholders,
    parse_placeholder,
)
from .service import ContractTemplateService

__all__ = [
    "ContractTemplateCatalogEntry",
    "ContractTemplateCatalogSection",
    "ContractTemplateCatalogService",
    "ContractTemplateDraftPayload",
    "ContractTemplateDraftRegistryAssignmentRecord",
    "ContractTemplateDraftRecord",
    "ContractTemplateExportError",
    "ContractTemplateExportResult",
    "ContractTemplateExportService",
    "ContractTemplateFormAutoField",
    "ContractTemplateFormChoice",
    "ContractTemplateFormDefinition",
    "ContractTemplateFormManualField",
    "ContractTemplateFormSelectorField",
    "ContractTemplateFormService",
    "ContractTemplateImportResult",
    "ContractTemplateIngestionError",
    "ContractTemplateOutputArtifactPayload",
    "ContractTemplateOutputArtifactRecord",
    "ContractTemplatePayload",
    "ContractTemplatePlaceholderBindingPayload",
    "ContractTemplatePlaceholderBindingRecord",
    "ContractTemplatePlaceholderPayload",
    "ContractTemplatePlaceholderRecord",
    "ContractTemplateResolvedSnapshotPayload",
    "ContractTemplateResolvedSnapshotRecord",
    "ContractTemplateRevisionAssetPayload",
    "ContractTemplateRevisionAssetRecord",
    "ContractTemplateRevisionPayload",
    "ContractTemplateRevisionRecord",
    "ContractTemplateRecord",
    "ContractTemplateScanDiagnostic",
    "ContractTemplateScanEntry",
    "ContractTemplateScanOccurrence",
    "ContractTemplateScanResult",
    "ContractTemplateService",
    "DOCXTemplateScanner",
    "HTMLTemplateBundle",
    "HTMLTemplateBundleError",
    "HTMLTemplateScanner",
    "InvalidPlaceholderError",
    "PagesTemplateAdapter",
    "PlaceholderOccurrence",
    "PlaceholderToken",
    "QtWebEngineHtmlPdfAdapter",
    "SUPPORTED_TEMPLATE_SOURCE_FORMATS",
    "TextutilDocxRenderAdapter",
    "base_symbol_for_indexed_placeholder",
    "build_contract_template_indexed_selection_key",
    "dedupe_placeholders",
    "detect_template_source_format",
    "extract_placeholders",
    "parse_placeholder",
]
